sudo: false

language: java

jdk:
    - oraclejdk8

install: true

script: gradle build

deploy:
    skip_cleanup: true
    provider: releases
    api_key:
        secure: Tv8gH7hGCj9KVHHYk74CcJGeF87bDo5hB4eBFiqxfLTzQPXrupZCjb/A1aZou25jd4FoHsFKlSCbwNJ9Vh/5WbuSr9xVDk7TPHmELr07F8NCY2nFgT7KP/wV0u5k8LECpRSmQ5Irc9tWe8YzL/oTRL4GXTxFOybAGX34KHZqqDI=
    file_glob: true
    file: "build/libs/HyperChat*.jar"
    on:
        tags: true
        repo: hyperfresh/mc-hyperchat

notifications:
    email: false
    irc:
        channels:
            - "irc.esper.net#hyperfresh"
        on_success: always
        on_failure: always